### ISSUE TITLE
Throw exception if client wants to begin second transaction

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-doctrine-adapter#3]
It should not be possible to start a second transaction if adapter is in an active transaction.

**Comment by Richtermeister** [comment]
@codeliner I see this decision is made on purpose, but I wonder why. In my current architecture I would like to persist domain events as part of a larger transaction which encapsulates other changes, but this check here prevents this: https://github.com/prooph/event-store-doctrine-adapter/blob/master/src/DoctrineEventStoreAdapter.php#L243-L245

Thank you for helping me understand the reason for this design.

**Comment by codeliner** [comment]
@Richtermeister The rule of thumb here is that one command (or action) should only cause changes in one aggregate. If multiple aggregates are effected by one action it is a good indicator that you've missed a concept in your domain. If you have an initial command triggered by the user and follow up commands automatically triggered by the system you can make use of a process manager (let me know if you need more information). 

However, if your use case really requires changes in multiple aggregates you can use an own transaction manager. The event store transaction is controlled from the outside so you can encapsulate other changes in one transaction but not in nested transactions as this resulted in a debugging nightmare in the past.

**Comment by Richtermeister** [comment]
@codeliner I see, and thank you for the quick response. Yes, I'm aware of the single AR transaction design rule and use of a process manager process manager for more complex cases. 

My issue is that I'd like to use the event store in a **non**-event-source situation. My AR is backed by a relational write-model which also happens to raise domain events (as part of CQRS, to update the view model, not to re-hydrate the model again). I am using the League/Tactician command bus with the Doctrine transactional middleware to ensure transactional integrity of a single command handling, and I would love to slot the persistence of domain events into another middleware, before the transaction is closed.

I greatly admire the separation of concerns you guys have accomplished between event storage and event sourcing needs, and I wonder if the event store might be more useful without assuming event sourcing use-cases, and move the enforcement of transaction handling to, say, the event-sourced repository implementations. I am happy to open a PR if you approve of this idea.

In the meantime I have "hacked around things" by making your transaction the main transaction, since there is only one shared the Doctrine connection at play.

Again, thank you for helping me understand. Have a great weekend.

**Comment by codeliner** [comment]
@Richtermeister very interesting thoughts. The event store is designed to be the primary storage mechanism for the write model. However, your use case is valid. The goal of prooph components is that you can mix and match them with other libraries and build your own system the way you like it/need it.

That said, I'd like to support your use case but we need to discuss it first.
@prolic is currently busy and may have not enough time the next two weeks. 
For now I've created a new issue: https://github.com/prooph/event-store/issues/150
to collect some ideas.
